from abc import ABC, abstractmethod
from typing import AsyncGenerator, List, Optional

from app.schemas.model import ModelInfo


class BaseProviderAdapter(ABC):
    """Abstract base class for all LLM provider adapters in ArenaX.

    All LLM provider integrations (e.g. OpenRouter, Google AI Studio, Groq, Cerebras, Mistral)
    must subclass this class and implement the required abstract methods.
    """

    @property
    @abstractmethod
    def provider_name(self) -> str:
        """Return the unique lowercase provider identifier (e.g. 'google', 'groq')."""
        pass

    @abstractmethod
    async def generate_response(
        self, prompt: str, model_id: str
    ) -> AsyncGenerator[str, None]:
        """Asynchronously stream chunks of text generated by the provider for a given model.

        Args:
            prompt: The user prompt or conversation input.
            model_id: The specific model ID to execute inference on.

        Yields:
            Text tokens/chunks as they arrive from the provider's streaming API.

        Raises:
            ProviderUnavailableError: If provider API is unreachable or fails.
            ProviderQuotaExceededError: If rate limit or quota is exhausted.
            ModelNotFoundError: If requested model_id is invalid for this adapter.
        """
        pass

    async def check_quota_available(self, model_id: str) -> bool:
        """Check if provider rate limits or daily quota allow a request for the specified model.

        Note: Currently defaults to returning True as Redis Quota Manager (Sub-phase 1.3)
        is deferred. When Redis Quota Manager is enabled, this method will query Redis.

        Args:
            model_id: The model ID to check.

        Returns:
            True if request is allowed under current quota, False otherwise.
        """
        return True

    @abstractmethod
    def get_supported_models(self) -> List[ModelInfo]:
        """Return a list of ModelInfo instances supported natively by this provider adapter."""
        pass

    def supports_model(self, model_id: str) -> bool:
        """Check if this adapter supports the given model_id."""
        return any(model.id == model_id for model in self.get_supported_models())
